### ISSUE TITLE
歌名(title)字段含有"/"会导致错误？

### ISSUE THREAD

**Issue by willia0** [anonymous5l/ncmdump#11]
大佬辛苦了！
在Ubuntu 18.04下正常编译，对整个文件夹运行，部分文件成功，后提示"段错误 (核心已转储)”；定位到是它引起了错误 “Imagine Dragons,Khalid - Thunder ／ Young Dumb & Broke (Medley).ncm”；
现已排除“&”的问题(歌名为Young Dumb & Broke 的ncm能正常处理)，故怀疑是歌名内符号“/”的锅。但我暂时找不到更多既是ncm格式又带“/”的音乐文件了，未能用其它文件复现。
罪魁祸首链接：https://music.163.com/#/song?id=525063410

**Comment by iyanging** [comment]
可能是路径非法符号，写个函数过滤/转化掉试试看

**Comment by anonymous5l** [comment]
already fix
