### ISSUE TITLE
请问下...你们的key都是怎么拿到的

### ISSUE THREAD

**Issue by wx-Yao** [anonymous5l/ncmdump#20]
还没找到这些工具的时候我尝试过看看ncm的hex，但是一顿操作没什么头绪。然后看你们的代码第一行就是core_key meta_key....

我只是纯好奇你们是怎么找到这个key的呀或者整个思路大概是什么样的。我reversing贼烂，可不可以大概给我个思路xio习xio习..

非常感谢，直接编译过了用得飞起。

**Comment by anonymous5l** [comment]
桌面端可以hook文件写入文件读取这块儿来获得算法基本就是ollydbg动态调试出来 移动端就IDA 动态调试so 基本原理差不多

**Comment by wx-Yao** [comment]
好的好的感谢。我再学学看
