### ISSUE TITLE
这个应该这么运行啊，运行main和运行ncmcryot都报错。

### ISSUE THREAD

**Issue by Loo-KING** [anonymous5l/ncmdump#31]
你们说的那个什么库taglib需要怎么弄啊。c没怎么学过搞不明白还请大佬帮帮我。
这个是编辑日志
编译单个文件...
--------
- 文件名: C:\Users\63439\Desktop\ncmdump-master\main.cpp
- 编译器名: TDM-GCC 4.9.2 64-bit Release

处理 C++ 源文件...
--------
- C++ 编译器: C:\Program Files (x86)\Dev-Cpp\MinGW64\bin\g++.exe
- 命令: g++.exe "C:\Users\63439\Desktop\ncmdump-master\main.cpp" -o "C:\Users\63439\Desktop\ncmdump-master\main.exe"  -I"C:\Program Files (x86)\Dev-Cpp\MinGW64\include" -I"C:\Program Files (x86)\Dev-Cpp\MinGW64\x86_64-w64-mingw32\include" -I"C:\Program Files (x86)\Dev-Cpp\MinGW64\lib\gcc\x86_64-w64-mingw32\4.9.2\include" -I"C:\Program Files (x86)\Dev-Cpp\MinGW64\lib\gcc\x86_64-w64-mingw32\4.9.2\include\c++" -L"C:\Program Files (x86)\Dev-Cpp\MinGW64\lib" -L"C:\Program Files (x86)\Dev-Cpp\MinGW64\x86_64-w64-mingw32\lib" -static-libgcc
C:\Users\63439\AppData\Local\Temp\ccibchfz.o:main.cpp:(.text+0xbc): undefined reference to `NeteaseCrypt::NeteaseCrypt(std::string const&)'
C:\Users\63439\AppData\Local\Temp\ccibchfz.o:main.cpp:(.text+0xe6): undefined reference to `NeteaseCrypt::Dump()'
C:\Users\63439\AppData\Local\Temp\ccibchfz.o:main.cpp:(.text+0xf2): undefined reference to `NeteaseCrypt::FixMetadata()'
C:\Users\63439\AppData\Local\Temp\ccibchfz.o:main.cpp:(.text+0x128): undefined reference to `NeteaseCrypt::~NeteaseCrypt()'
C:\Users\63439\AppData\Local\Temp\ccibchfz.o:main.cpp:(.text+0x174): undefined reference to `NeteaseCrypt::~NeteaseCrypt()'
C:\Users\63439\AppData\Local\Temp\ccibchfz.o:main.cpp:(.text+0x1a2): undefined reference to `NeteaseCrypt::~NeteaseCrypt()'
collect2.exe: error: ld returned 1 exit status

谢谢

**Comment by Loo-KING** [comment]
emm看评论里好多都是Linux，我用的windows下的devc++应该怎么使用啊

**Comment by MCredbear** [comment]
> emm看评论里好多都是Linux，我用的windows下的devc++应该怎么使用啊

那我就不能确保你的依赖没问题了，装那个依赖的话你百度一下taglib看看有没有windows版本，然后你开cmd到那个源码目录下，这个目录里面有个叫Makefile的文件，你用记事本打开，然后把里面的那行命令复制到cmd里运行，会生成ncmdump（我也不清楚是不是ncmdump.exe）

**Comment by Loo-KING** [comment]
> emm看评论里好多都是Linux，我用的windows下的devc++应该怎么使用啊
> 
> 那我就不能确保你的依赖没问题了，装那个依赖的话你百度一下taglib看看有没有windows版本，然后你开cmd到那个源码目录下，这个目录里面有个叫Makefile的文件，你用记事本打开，然后把里面的那行命令复制到cmd里运行，会生成ncmdump（我也不清楚是不是ncmdump.exe）

Windows的taglib已经下好了，是下载就行了吗不用这么处理吗？然后ncmdump那个目录下运行makfile里的话显示   文件名、目录名或卷标语法不正确。  这是怎么回事呀

**Comment by MCredbear** [comment]
> > emm看评论里好多都是Linux，我用的windows下的devc++应该怎么使用啊
> > 那我就不能确保你的依赖没问题了，装那个依赖的话你百度一下taglib看看有没有windows版本，然后你开cmd到那个源码目录下，这个目录里面有个叫Makefile的文件，你用记事本打开，然后把里面的那行命令复制到cmd里运行，会生成ncmdump（我也不清楚是不是ncmdump.exe）
> 
> Windows的taglib已经下好了，是下载就行了吗不用这么处理吗？然后ncmdump那个目录下运行makfile里的话显示 文件名、目录名或卷标语法不正确。 这是怎么回事呀

taglib下好了当然要安装啊。Makefile里只有第2行和第3行的命令要运行，应该是生成ncmdump而不是x.exe

**Comment by Loo-KING** [comment]
> emm看评论里好多都是Linux，我用的windows下的devc++应该怎么使用啊
> 那我就不能确保你的依赖没问题了，装那个依赖的话你百度一下taglib看看有没有windows版本，然后你开cmd到那个源码目录下，这个目录里面有个叫Makefile的文件，你用记事本打开，然后把里面的那行命令复制到cmd里运行，会生成ncmdump（我也不清楚是不是ncmdump.exe）
> 
> Windows的taglib已经下好了，是下载就行了吗不用这么处理吗？然后ncmdump那个目录下运行makfile里的话显示 文件名、目录名或卷标语法不正确。 这是怎么回事呀
> 
> taglib下好了当然要安装啊。Makefile里只有第2行和第3行的命令要运行，应该是生成ncmdump而不是x.exe

emmm找了半天还是不知道这么安装taglib。但是我看这个文件夹里有一个taglib.doxyfile的文件，是不是应该有了。记事本里写的是这样的  
all:
	g++ main.cpp cJSON.cpp aes.cpp ncmcrypt.cpp -o ncmdump -ltag
	strip ncmdump

install: all
	mv ncmdump /usr/local/bin

请问大佬具体应该这么安装这么操作呀，就这样用cmd就行了就不需要dev这种编译器了吧

**Comment by MCredbear** [comment]
> > emm看评论里好多都是Linux，我用的windows下的devc++应该怎么使用啊
> > 那我就不能确保你的依赖没问题了，装那个依赖的话你百度一下taglib看看有没有windows版本，然后你开cmd到那个源码目录下，这个目录里面有个叫Makefile的文件，你用记事本打开，然后把里面的那行命令复制到cmd里运行，会生成ncmdump（我也不清楚是不是ncmdump.exe）
> > Windows的taglib已经下好了，是下载就行了吗不用这么处理吗？然后ncmdump那个目录下运行makfile里的话显示 文件名、目录名或卷标语法不正确。 这是怎么回事呀
> > taglib下好了当然要安装啊。Makefile里只有第2行和第3行的命令要运行，应该是生成ncmdump而不是x.exe
> 
> emmm找了半天还是不知道这么安装taglib。但是我看这个文件夹里有一个taglib.doxyfile的文件，是不是应该有了。记事本里写的是这样的
> all:
> g++ main.cpp cJSON.cpp aes.cpp ncmcrypt.cpp -o ncmdump -ltag
> strip ncmdump
> 
> install: all
> mv ncmdump /usr/local/bin
> 
> 请问大佬具体应该这么安装这么操作呀，就这样用cmd就行了就不需要dev这种编译器了吧

我觉得你应该百度一个windows安装taglib的教程，还有dev不是编译器，编译的命令就是all后面的那两行

**Comment by Loo-KING** [comment]
taglib安装用cmake然后又装cmake然后又调环境最后也没弄成。然后就默认源码那个文件里的可以用直接跑命令
我复制的两行命令系统自己给分开了  
一行   g++ main.cpp cJSON.cpp aes.cpp ncmcrypt.cpp -o ncmdump -ltag  说是g++' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
然后就一行strip ncmdump 也运行不了。
我觉得我可以放弃了，程序写的很好但我不会用。我等着什么时候有那种简易操作的版本我再用吧现在太难了。也谢谢大佬这么耐心指导我。

**Comment by MCredbear** [comment]
> taglib安装用cmake然后又装cmake然后又调环境最后也没弄成。然后就默认源码那个文件里的可以用直接跑命令
> 我复制的两行命令系统自己给分开了
> 一行 g++ main.cpp cJSON.cpp aes.cpp ncmcrypt.cpp -o ncmdump -ltag 说是g++' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 然后就一行strip ncmdump 也运行不了。
> 我觉得我可以放弃了，程序写的很好但我不会用。我等着什么时候有那种简易操作的版本我再用吧现在太难了。也谢谢大佬这么耐心指导我。

你把那个g++换成gcc试试？

**Comment by Loo-KING** [comment]
> taglib安装用cmake然后又装cmake然后又调环境最后也没弄成。然后就默认源码那个文件里的可以用直接跑命令
> 我复制的两行命令系统自己给分开了
> 一行 g++ main.cpp cJSON.cpp aes.cpp ncmcrypt.cpp -o ncmdump -ltag 说是g++' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 然后就一行strip ncmdump 也运行不了。
> 我觉得我可以放弃了，程序写的很好但我不会用。我等着什么时候有那种简易操作的版本我再用吧现在太难了。也谢谢大佬这么耐心指导我。
> 
> 你把那个g++换成gcc试试？

C:\Users\63439\Desktop\ncmdump-master>gcc main.cpp cJSON.cpp aes.cpp ncmcrypt.cpp -o ncmdump -ltag
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

还是不行，哭了😭

**Comment by MCredbear** [comment]
> > taglib安装用cmake然后又装cmake然后又调环境最后也没弄成。然后就默认源码那个文件里的可以用直接跑命令
> > 我复制的两行命令系统自己给分开了
> > 一行 g++ main.cpp cJSON.cpp aes.cpp ncmcrypt.cpp -o ncmdump -ltag 说是g++' 不是内部或外部命令，也不是可运行的程序
> > 或批处理文件。
> > 然后就一行strip ncmdump 也运行不了。
> > 我觉得我可以放弃了，程序写的很好但我不会用。我等着什么时候有那种简易操作的版本我再用吧现在太难了。也谢谢大佬这么耐心指导我。
> > 你把那个g++换成gcc试试？
> 
> C:\Users\63439\Desktop\ncmdump-master>gcc main.cpp cJSON.cpp aes.cpp ncmcrypt.cpp -o ncmdump -ltag
> 'gcc' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 
> 还是不行，哭了

emm，我记得devc会自动安装gcc的啊。。。好吧希望你能换linux系统。

**Comment by Loo-KING** [comment]
> taglib安装用cmake然后又装cmake然后又调环境最后也没弄成。然后就默认源码那个文件里的可以用直接跑命令
> 我复制的两行命令系统自己给分开了
> 一行 g++ main.cpp cJSON.cpp aes.cpp ncmcrypt.cpp -o ncmdump -ltag 说是g++' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 然后就一行strip ncmdump 也运行不了。
> 我觉得我可以放弃了，程序写的很好但我不会用。我等着什么时候有那种简易操作的版本我再用吧现在太难了。也谢谢大佬这么耐心指导我。
> 你把那个g++换成gcc试试？
> 
> C:\Users\63439\Desktop\ncmdump-master>gcc main.cpp cJSON.cpp aes.cpp ncmcrypt.cpp -o ncmdump -ltag
> 'gcc' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 还是不行，哭了
> 
> emm，我记得devc会自动安装gcc的啊。。。好吧希望你能换linux系统。
嗯嗯当时讲的就是会自动都装好，Linux系统是这么装的啊

**Comment by MCredbear** [comment]
> > taglib安装用cmake然后又装cmake然后又调环境最后也没弄成。然后就默认源码那个文件里的可以用直接跑命令
> > 我复制的两行命令系统自己给分开了
> > 一行 g++ main.cpp cJSON.cpp aes.cpp ncmcrypt.cpp -o ncmdump -ltag 说是g++' 不是内部或外部命令，也不是可运行的程序
> > 或批处理文件。
> > 然后就一行strip ncmdump 也运行不了。
> > 我觉得我可以放弃了，程序写的很好但我不会用。我等着什么时候有那种简易操作的版本我再用吧现在太难了。也谢谢大佬这么耐心指导我。
> > 你把那个g++换成gcc试试？
> > C:\Users\63439\Desktop\ncmdump-master>gcc main.cpp cJSON.cpp aes.cpp ncmcrypt.cpp -o ncmdump -ltag
> > 'gcc' 不是内部或外部命令，也不是可运行的程序
> > 或批处理文件。
> > 还是不行，哭了
> > emm，我记得devc会自动安装gcc的啊。。。好吧希望你能换linux系统。
> > 嗯嗯当时讲的就是会自动都装好，Linux系统是这么装的啊

我刚刚发的那个apt的命令只适用于debian系的linux系统哦

**Comment by anonymous5l** [comment]
有windows版本的repo不用
https://github.com/anonymous5l/ncmdump-gui/releases/tag/fully
需要.NET Framework4.6.1

**Comment by Loo-KING** [comment]
> 有windows版本的repo不用
> https://github.com/anonymous5l/ncmdump-gui/releases/tag/fully
> 需要.NET Framework4.6.1

哇好用！！！！！！谢谢
