### ISSUE TITLE
你好请问转好之后的文件名为啥跟源文件不一样（少了歌手）

### ISSUE THREAD

**Issue by ManyMeanings** [anonymous5l/ncmdump#33]

**Comment by MCredbear** [comment]
可能和taglib的版本有关？我在x86的deepin(stable应该是）上编译的时候也是你这样，但是在arm64的debian(sid)上编译是没这个问题的

**Comment by Yeamy** [comment]
源码里有看到，是按ID3信息读取的信息来保存的，可以使用[JAVA版](https://github.com/Yeamy/ncmdump/releases)，这个是按源文件名保存的
