### ISSUE TITLE
Segmentation fault (core dumped), when running

### ISSUE THREAD

**Issue by nakidz** [anonymous5l/ncmdump#5]
Make successfully. 
But show "Segmentation fault (core dumped)" when running ncmdump.
Tried ubuntu 14.04 and win10 Linux subsystem, same result. Any help?

**Comment by anonymous5l** [comment]
provide music name or file to me

**Comment by nakidz** [comment]
Lianne La Havas - Starry Starry Night，320k mp3

**Comment by nakidz** [comment]
For some unknown reason，i can't connect tuna source and i just used the default apt-get source.
Maybe it causes this fault, but can't confirm at this time.

**Comment by iyanging** [comment]
@nakidz  Maybe you should try `C++` branch, and that's the reason why `C++` branch exists.
