### ISSUE TITLE
Compile Error on macOS

### ISSUE THREAD

**Issue by CaiPeterCai** [anonymous5l/ncmdump#6]
ncmdump git:(master) ✗ make
g++ main.cpp cJSON.cpp -o ncmdump -lcrypto -ltag -lz
In file included from main.cpp:10:
In file included from /usr/local/include/taglib/flacfile.h:31:
In file included from /usr/local/include/taglib/tlist.h:263:
In file included from /usr/local/include/taglib/tlist.tcc:27:
/usr/local/include/taglib/trefcounter.h:83:18: warning: 'OSAtomicIncrement32Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_fetch_add() from <atomic> instead [-Wdeprecated-declarations]
    void ref() { OSAtomicIncrement32Barrier(const_cast<int32_t*>(&refCount)); }
                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libkern/OSAtomicDeprecated.h:182:9: note: 'OSAtomicIncrement32Barrier' has been explicitly marked deprecated here
int32_t OSAtomicIncrement32Barrier( volatile int32_t *__theValue );
        ^
In file included from main.cpp:10:
In file included from /usr/local/include/taglib/flacfile.h:31:
In file included from /usr/local/include/taglib/tlist.h:263:
In file included from /usr/local/include/taglib/tlist.tcc:27:
/usr/local/include/taglib/trefcounter.h:84:29: warning: 'OSAtomicDecrement32Barrier' is deprecated: first deprecated in macOS 10.12 - Use std::atomic_fetch_sub() from <atomic> instead [-Wdeprecated-declarations]
    bool deref() { return ! OSAtomicDecrement32Barrier(const_cast<int32_t*>(&refCount)); }
                            ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libkern/OSAtomicDeprecated.h:201:9: note: 'OSAtomicDecrement32Barrier' has been explicitly marked deprecated here
int32_t OSAtomicDecrement32Barrier( volatile int32_t *__theValue );
        ^
2 warnings generated.
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [all] Error 1

/---------------------------------------------------------------------------------------------------/
gcc -v

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin18.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by CaiPeterCai** [comment]
https://github.com/google/leveldb/pull/422

**Comment by CaiPeterCai** [comment]
[Bypass OSMemoryBarrier() warning on Mac](https://github.com/google/leveldb/commit/594cc987af2e0af6417c4ac2b947ee8cdad59e5e)

**Comment by CaiPeterCai** [comment]
[warning: 'OSAtomicDecrement32Barrier' is deprecated: first deprecated in macOS 10.12](https://github.com/supermihi/pytaglib/issues/41)
[Build fails on mac os x 10.13.3 (and Fedora)](https://github.com/supermihi/pytaglib/issues/42)

**Comment by anonymous5l** [comment]
the problem source from taglib third party i can't fix it try use manual compile taglib and install to default path can be solve your problem

[taglib](https://github.com/taglib/taglib)

**Comment by iyanging** [comment]
i do think the real problem is that you do not have the crypto library, so make it installed and then retry
